avance del template
Tamay-Flores-Bryan-Armando/tercer-parcial-is pull request #1
Opened 2021-12-01 22:29 UTC by Jejiro53

corregí y avance el template como lo tenía antes, le hice unos cambios y avance un poco.

2021-12-01 23:36 UTC, abraham1669 requested changes

2021-12-01 23:36 UTC, abraham1669 commented on Proyecto Template parcial 3/Proyecto Template.html
>          <font color="#007FFF"><p>About</p></font>
No se debe de usar la etiqueta font, ya que esta etiqueta ha sido depreciada en html5, se debe de aplicar una clase a la etiqueta p, ejemplo:
te dejo una referencia del por qué no se debe ocupar [Font etiqueta](https://developer.mozilla.org/es/docs/Web/HTML/Element/font)
```
.paragraph:{
 color: #007fff;
}
```

2021-12-01 23:36 UTC, abraham1669 commented on Proyecto Template parcial 3/Proyecto Template.html
> -    <div class="container-titulo">
Si estás ocupando Bootstrap, no existe la clase container-titulo, es solo container

2021-12-01 23:36 UTC, abraham1669 commented on Proyecto Template parcial 3/Proyecto Template.html
>         <div class="row2">
Si estas ocupando Bootstrap, no existe una clase row2

2021-12-08 23:16 UTC, Tamay-Flores-Bryan-Armando approved these changes

2021-12-08 23:43 UTC, merged